name: Build PMMP PHP (GLIBC 2.28 compatible)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:10

    steps:
      - name: Disable interactive (tzdata fix)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
          echo "Europe/Warsaw" > /etc/timezone

      - name: Fix sources (Debian 10 archive)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list
          sed -i 's/security.debian.org/archive.debian.org/g' /etc/apt/sources.list
          apt update

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt install -y \
          tzdata git curl wget \
          build-essential autoconf automake libtool pkg-config \
          bison re2c \
          libsqlite3-dev libssl-dev zlib1g-dev \
          libxml2-dev libcurl4-openssl-dev

      - name: Clone PHP-Binaries
        run: git clone https://github.com/pmmp/PHP-Binaries.git

      - name: Build PHP
        run: |
          cd PHP-Binaries
          chmod +x compile.sh
          ./compile.sh -j$(nproc)

      - name: Prepare output
        run: |
          mkdir output
          cp -r PHP-Binaries/bin output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmmp-php-glibc228
          path: output/
