name: Build PMMP PHP (stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:11

    steps:
      - name: Set non-interactive + timezone
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime
          echo "Europe/Warsaw" > /etc/timezone

      - name: Update system
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get -y dist-upgrade

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get install -y \
          git curl wget \
          build-essential autoconf automake libtool libtool-bin pkg-config \
          cmake make gcc g++ \
          bison re2c \
          libsqlite3-dev libssl-dev zlib1g-dev \
          libxml2-dev libcurl4-openssl-dev

      - name: Clone PHP-Binaries
        run: git clone https://github.com/pmmp/PHP-Binaries.git

      - name: Build PHP
        run: |
          cd PHP-Binaries
          chmod +x compile.sh
          ./compile.sh -P5 -j$(nproc)

      - name: Prepare output
        run: |
          mkdir -p output
          cp -r PHP-Binaries/bin output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmmp-php
          path: output/
